
name: Build & Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - master
      - stage

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: matters-test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Lint
        run: |
          npm run lint \
          && npm run format:check
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          MATTERS_ENV: test
          MATTERS_PG_HOST: localhost
          MATTERS_PG_USER: postgres
          MATTERS_PG_PASSWORD: postgres
          MATTERS_PG_DATABASE: matters-test
          MATTERS_NEW_FEATURE_TAG_ID: 1
          MATTERS_PG_RO_CONNECTION_STRING: postgresql://postgres:postgres@localhost/test_matters-test


